version: 2
jobs:
  build_x11:
    machine: true
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get -y install scons
            sudo apt-get -y install build-essential subversion cmake xorg-dev libgl1-mesa-dev libglu-dev
      - run:
          name: build X11
          command: scons platform=x11

  build_osx:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run: brew install scons
      - run:
          name: build OSX
          command: scons platform=osx

  build_ios:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run: brew install scons
      - run:
          name: build iOS
          command: |
            scons p=iphone tools=no bits=32 target=release arch=arm
            scons p=iphone tools=no bits=64 target=release arch=arm64
            lipo -create bin/godot.iphone.opt.32 bin/godot.iphone.opt.64 -output bin/godot.iphone.opt.universal

  build_android:
    docker:
      - image: lumbrel/android:api-24-alpha-ndk
    environment:
      JVM_OPTS: -Xmx3200m
      ANDROID_NDK_ROOT: /opt/android/sdk/ndk-bundle
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get -y install scons
            sudo apt-get -y install build-essential subversion cmake xorg-dev libgl1-mesa-dev libglu-dev
      - run:
          name: Generate project
          command: scons platform=android target=release
      - run:
          name: Build project
          command: |
            cd platform/android/java
            ./gradlew build

workflows:
  version: 2
  build_all_platforms:
    jobs:
      - build_x11
      - build_osx
      - build_ios
      - build_android
