machine:
  pre:
    - sudo apt-get update
    - sudo apt-get -y install scons
    - sudo apt-get -y install build-essential subversion cmake xorg-dev libgl1-mesa-dev libglu-dev

compile:
  override:
    - scons platform=x11
